add_newline = true

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[deno]
format = "via [🦕 $version](green bold) "

[docker_context]
format = "via [🐋 $context](blue bold)"

[git_commit]
tag_symbol = "🔖 "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[memory_usage]
disabled = false
threshold = -1
symbol = "🐏"
format = "via $symbol [${ram}\\(${ram_pct}\\)]($style) "
style = "bold dimmed green"

[nodejs]
format = "via [🍏 $version](bold green) "

[package]
disabled = true

[rust]
format = "via [🦀 $version](red bold)"

[username]
style_user = "white bold"
style_root = "black bold"
format = "user: [$user]($style) "
disabled = false
show_always = true

[time]
disabled = false
format = '🕙[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "local"
